version: '2.1'

# docker network create mediaserver

networks:
    mediaserver:
        external: true

services:

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/sonarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/series:/tv
        ports:
            - "8989:8989"
        networks:
            - mediaserver

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/radarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/movies:/movies
        ports:
            - "7878:7878"
        networks:
            - mediaserver

    bazarr:
        container_name: bazarr
        image: ghcr.io/linuxserver/bazarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/bazarr:/config
            - ./media/storage/movies:/movies
            - ./media/storage/series:/tv
        ports:
            - 6767:6767
        networks:
          - mediaserver
