version: '2.1'

networks:
    mediaserver:
        external: true

services:

    transmission:
        container_name: transmission
        build:
            context: ./
            dockerfile: ./transmission/Dockerfile
        user: root
        privileged: true
        restart: unless-stopped
        ports:
            - "9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/transmission:/var/lib/transmission-daemon/info
            #set transmission or sonarr download folder to /downloads
            - ./media/downloads/complete:/downloads
            - ./media/downloads/temp:/var/lib/transmission-daemon/incomplete
        networks:
            - mediaserver

    jackett:
        container_name: jackett
        image: linuxserver/jackett
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/jackett:/config
            - ./media/downloads/complete:/downloads
        ports:
            - "9117:9117"
        networks:
            - mediaserver