version: '2.1'

networks:
    mediaserver:
        driver: bridge

services:

    emby:
        image: emby/embyserver_arm32v7:latest
        volumes:
            - ./media/config/emby:/config
            - ./media/data/emby:/data
            - ./media/storage:/mnt/storage
            # USB Storage
            - /mnt/usb:/usb
        ports:
            - "8096:8096"
            - "8920:8920"
        environment:
            - UID=1000
            - GID=100
            - GIDLIST=100
        networks:
            - mediaserver

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
            - PUID=1000
            - PGID=1000
        volumes:
            - ./media/config/sonarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/series:/tv
            # USB Storage
            - /mnt/usb:/usb
        ports:
            - "8989:8989"
        networks:
            - mediaserver

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
            - PUID=1000
            - PGID=1000
        volumes:
            - ./media/config/radarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/movies:/movies
            # USB Storage
            - /mnt/usb:/usb
        ports:
            - "7878:7878"
        networks:
            - mediaserver