version: '2.1'

networks:
    mediaserver:
        driver: bridge

services:

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/sonarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/series:/tv
            # USB Storage
            #- /mnt/usb:/usb
        ports:
            - "8989:8989"
        networks:
            - mediaserver

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/radarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/movies:/movies
            # USB Storage
            #- /mnt/usb:/usb
        ports:
            - "7878:7878"
        networks:
            - mediaserver
    
    lidarr:
        container_name: lidarr
        image: linuxserver/lidarr
        user: root
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Asia/Dubai
        volumes:
            - ./media/config/lidarr:/config
            - ./media/downloads/complete:/downloads
            - ./media/storage/music:/music
            # USB Storage
            #- /mnt/usb:/usb
        ports:
            - "8686:8686"
        networks:
            - mediaserver
